services:
  node1:
    build: .
    container_name: node1
    volumes:
      - ./data/node1:/app/data
    command: ["node", "dist/main.js", "node", "run", "--data-dir", "/app/data"]

  node2:
    build: .
    container_name: node2
    volumes:
      - ./data/node2:/app/data
    command: ["node", "dist/main.js", "node", "run", "--data-dir", "/app/data"]

  node3:
    build: .
    container_name: node3
    volumes:
      - ./data/node3:/app/data
    command: ["node", "dist/main.js", "node", "run", "--data-dir", "/app/data"]